### PR TITLE
Update "New Beats with UI" PR to latest main

### PR DESCRIPTION
**Pull request by Holzhaus**
Merge conflicts resolved.

I still need to double-check if my adaption of the Serato Beatgrid exporter to the new API works properly.

There are two failing EngineSyncTests: 

    266 - EngineSyncTest.UserTweakPreservedInSeek (Failed)
    270 - EngineSyncTest.SeekStayInPhase (Failed)

@ywwg Could you take a look?
@mr-smidge Please check if my changes to the djinterop code are correct.

### CODE REVIEW

**Comment by ywwg** [comment]
Doesn't seem to build:

```
In file included from /home/owen/src/github/mixxx/src/track/beat.h:9,
                 from /home/owen/src/github/mixxx/src/widget/wbeatmenu.h:6,
                 from /home/owen/src/github/mixxx/cbuild/mixxx-lib_autogen/WFD7YQQOTJ/moc_wbeatmenu.cpp:9,
                 from /home/owen/src/github/mixxx/cbuild/mixxx-lib_autogen/mocs_compilation.cpp:3:
/home/owen/src/github/mixxx/src/track/timesignature.h:19:52: error: expected ‘)’ before ‘timeSignatureProto’
   19 |     explicit TimeSignature(track::io::TimeSignature timeSignatureProto) {
      |                           ~                        ^~~~~~~~~~~~~~~~~~~
      |                                                    )
/home/owen/src/github/mixxx/src/track/timesignature.h:48:16: error: ‘TimeSignature’ in namespace ‘mixxx::track::io’ does not name a type
   48 |     track::io::TimeSignature m_timeSignature;
      |                ^~~~~~~~~~~~~
/home/owen/src/github/mixxx/src/track/timesignature.h: In member function ‘void mixxx::TimeSignature::setBeatsPerBar(int)’:
/home/owen/src/github/mixxx/src/track/timesignature.h:26:9: error: ‘m_timeSignature’ was not declared in this scope; did you mean ‘setTimeSignature’?
   26 |         m_timeSignature.set_beats_per_bar(beatsPerBar);
      |         ^~~~~~~~~~~~~~~
      |         setTimeSignature
/home/owen/src/github/mixxx/src/track/timesignature.h: In member function ‘void mixxx::TimeSignature::setNoteValue(int)’:
/home/owen/src/github/mixxx/src/track/timesignature.h:30:9: error: ‘m_timeSignature’ was not declared in this scope; did you mean ‘setTimeSignature’?
   30 |         m_timeSignature.set_note_value(noteValue);
      |         ^~~~~~~~~~~~~~~
      |         setTimeSignature
/home/owen/src/github/mixxx/src/track/timesignature.h: In member function ‘int mixxx::TimeSignature::getBeatsPerBar() const’:
/home/owen/src/github/mixxx/src/track/timesignature.h:39:16: error: ‘m_timeSignature’ was not declared in this scope; did you mean ‘setTimeSignature’?
   39 |         return m_timeSignature.beats_per_bar();
      |                ^~~~~~~~~~~~~~~
      |                setTimeSignature
/home/owen/src/github/mixxx/src/track/timesignature.h: In member function ‘int mixxx::TimeSignature::getNoteValue() const’:
/home/owen/src/github/mixxx/src/track/timesignature.h:43:16: error: ‘m_timeSignature’ was not declared in this scope; did you mean ‘setTimeSignature’?
   43 |         return m_timeSignature.note_value();
      |                ^~~~~~~~~~~~~~~
      |                setTimeSignature
```

and on

**Comment by Holzhaus** [comment]
@ywwg I cannot reproduce it. Did you try with a clean build dir?

**Comment by mr-smidge** [comment]
The djinterop code looks good from a quick glance.  The branch built fine for me (Linux Mint 20, g++ 9.3.0, QT 5.12.8), and an example export also worked fine. :+1:

**Comment by Holzhaus** [comment]
@hacksdump I only fixed conflicts and some warnings/bugs. Here what I did:
- I pulled merged latest main into your branch and resolved the conflicts.
- Fixed Qt deprecation warnings for Qt  >= 5.11
- Replaced `cend`/`cbegin` in Beats class since that's not supported on all platforms apparently
- Fixed all gcc/clazy/clang-tidy/float-conversion warnings
- Replaced `std::optional<T>::value()` with `*std::optional<T>` because that's not supported on all platforms
- Fixed a bug in BeatsTest where you dereference a member of a `std::nullopt`
- Fixed a bug in `2.3`/`main` that caused the sample rate in EngineControls to be wrong after a track load. You divide by the sample rate, that could lead to NaN position values in engine without this fix: https://github.com/mixxxdj/mixxx/pull/3655 (@daschuer is cleaning that up in https://github.com/mixxxdj/mixxx/pull/3656)
- Merge main again and resolve the conflicts

We still have one failing test in CueControlTest on macOS and a bunch of failing tests on Windows that need to be fixed: https://github.com/Holzhaus/mixxx/actions/runs/599312735

Here are the changes in this branch:
```
$ git log new-beats-with-ui ^hacksdump/new-beats-with-ui ^upstream/main --oneline
d51caa7692 (HEAD -> new-beats-with-ui, origin/new-beats-with-ui) Merge branch 'main' of github.com:mixxxdj/mixxx into new-beats-with-ui
d1967a7cdb BeatsTest: Fix expected return value for Beats::findNthBeat
c5a39037bc EngineBuffer: Use sample/frame conversion functions from frameadapter.h
a759b109db Merge branch 'main' of github.com:mixxxdj/mixxx into new-beats-with-ui
2b0ecad9ed track: Fix some clang-tidy warnings
a10b7a4cef Fix more clazy warnings
9475a4d4ec WaveformBeat: Fix clazy warnings
7cac45b49a Beats: Fix more clazy warnings
f8eda948b2 WaveformRenderBeat: Don't use std::optional<T>::value()
10e60ad9d2 waveformbeat: Fix -Wfloat-conversion warning for QFont.setPixelSize
6e3da98b1a track: Pass arguments by reference (fixes clazy warnings)
9a2d25079b Beats: Replace cbegin/cend for compatibility reasons
2ff46a2864 WaveformBeatMarker: Fix build with Qt < 5.11.0
09af57ce05 Merge branch 'main' of github.com:mixxxdj/mixxx into new-beats-with-ui
```

**Comment by Be-ing** [comment]
@hacksdump could you merge this now? Alternatively someone could open another PR for the upstream repo.

**Comment by hacksdump** [comment]
Thanks for handling the main merge. I checked this and the build and test look fine. So I will continue to merge this into my branch.

**Comment by Holzhaus** [comment]
> test look fine

There are still failing tests on Windows and macOS (The CI builds don't run until you merge the PR), so it'd be great of you could investigate what could have caused this. Other than than I think this branch is ready to merge into main (after some more code review/manual testing of course).

If you want to work on the new editing UI, please do so in a separate branch, so that the diff doesn't get much larger.

**Pull request merged**
